C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:56: RuntimeWarning: divide by zero encountered in scalar divide
  dPdm = -(G * m_r * rho / r**2) * (1 + P / (rho * c**2)) * (1 + 4 * np.pi * r**3 * P / (m_r * c**2)) / (1 - 2 * G * m_r / (r * c**2))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:56: RuntimeWarning: invalid value encountered in scalar multiply
  dPdm = -(G * m_r * rho / r**2) * (1 + P / (rho * c**2)) * (1 + 4 * np.pi * r**3 * P / (m_r * c**2)) / (1 - 2 * G * m_r / (r * c**2))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:102: ODEintWarning: Excess accuracy requested (tolerances too small). Run with full_output = 1 to get quantitative information.
  sol = odeint(TOV_equations, y_0, [mass[j-1], mass[j]], args=(M, R))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:102: ODEintWarning: Excess work done on this call (perhaps wrong Dfun type). Run with full_output = 1 to get quantitative information.
  sol = odeint(TOV_equations, y_0, [mass[j-1], mass[j]], args=(M, R))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:55: RuntimeWarning: divide by zero encountered in scalar divide
  drdm = 1 / (4 * np.pi * rho * r**2)
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:56: RuntimeWarning: invalid value encountered in scalar divide
  dPdm = -(G * m_r * rho / r**2) * (1 + P / (rho * c**2)) * (1 + 4 * np.pi * r**3 * P / (m_r * c**2)) / (1 - 2 * G * m_r / (r * c**2))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:73: RuntimeWarning: invalid value encountered in divide
  dY_edt = (Gamma_pc - Gamma_ec) / rho
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:82: RuntimeWarning: divide by zero encountered in divide
  omega_r = omega * R**2 / r**2
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:83: RuntimeWarning: invalid value encountered in multiply
  P_rot = 1/3 * rho * (omega_r * r)**2
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:85: RuntimeWarning: divide by zero encountered in divide
  B = B_0 * (R / r)**2
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:102: ODEintWarning: Illegal input detected (internal error). Run with full_output = 1 to get quantitative information.
  sol = odeint(TOV_equations, y_0, [mass[j-1], mass[j]], args=(M, R))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:102: ODEintWarning: Run terminated (internal error). Run with full_output = 1 to get quantitative information.
  sol = odeint(TOV_equations, y_0, [mass[j-1], mass[j]], args=(M, R))
C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py:127: RuntimeWarning: divide by zero encountered in log10
  im = ax1.pcolormesh(radius[frame], radius[frame], np.log10(rho[frame]), cmap='viridis', shading='auto')
Traceback (most recent call last):
  File "C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py", line 148, in <module>
    anim = FuncAnimation(fig, animate, frames=len(t), interval=50, blit=True)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 1693, in __init__
    super().__init__(fig, **kwargs)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 1417, in __init__
    super().__init__(fig, event_source=event_source, *args, **kwargs)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 888, in __init__
    self._setup_blit()
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 1216, in _setup_blit
    self._init_draw()
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 1747, in _init_draw
    self._draw_frame(frame_data)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 1766, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "C:\Users\matti\Documents\GitHub\Black_holes\bin\bh_creation.py", line 127, in animate
    im = ax1.pcolormesh(radius[frame], radius[frame], np.log10(rho[frame]), cmap='viridis', shading='auto')
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\__init__.py", line 1486, in inner
    return func(
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\axes\_axes.py", line 6428, in pcolormesh
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\axes\_axes.py", line 5951, in _pcolorargs
    nrows, ncols = C.shape[:2]
ValueError: not enough values to unpack (expected 2, got 1)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\matti\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 228, in filter_destroy
    CloseEvent("close_event", self)._process()
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\backend_bases.py", line 1231, in _process
    self.canvas.callbacks.process(self.name, self)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\cbook.py", line 303, in process
    self.exception_handler(exc)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\cbook.py", line 87, in _exception_printer
    raise exc
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\cbook.py", line 298, in process
    func(*args, **kwargs)
  File "C:\Users\matti\Documents\GitHub\Black_holes\.venv\lib\site-packages\matplotlib\animation.py", line 922, in _stop
    self._fig.canvas.mpl_disconnect(self._resize_id)
AttributeError: 'FuncAnimation' object has no attribute '_resize_id'